export default {

  // App Config
  APP_CONFIG_SET: 'APP_CONFIG_SET',

  // App States
  APP_SHOW_PAGE: 'APP_SHOW_PAGE',
  APP_PLATFORM_SET: 'APP_PLATFORM_SET',
  APP_SIDENAV_TOGGLE: 'APP_SIDENAV_TOGGLE',
  APP_NAVBAR_ACTIVE: 'APP_NAVBAR_ACTIVE',
  APP_WINDOW_RESIZE: 'APP_WINDOW_RESIZE',

  // Crypto Markets State
  CRYP_STATS_MARKETS_GET: 'CRYP_STATS_MARKETS_GET'
};
